#!/usr/bin/env python

import rospy # ROS Python library
from std_msgs.msg import String # Standard message library

def talker():
    # Initialize ROS node
    # name for our 'talker' node 
    rospy.init_node('talker', anonymous=True)

    # Create publisher
    #we specify the topic name, then type of message then the queue size
    pub = rospy.Publisher('chatter', String, queue_size=10)

    # Set loop rate
    rate = rospy.Rate(10)# 10hz

    # Create message
    count = 0
    while not rospy.is_shutdown():
        hello_str = "Hello world %s" % count
        rospy.loginfo(hello_str)

        # Publish message
        pub.publish(hello_str)

        # Sleep for remaining time to maintain loop rate
        rate.sleep()
        count += 1

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
